## Site Meta ##
# The title of the website.
title: "Nizar's Photography"
# The description of the website
description: "My photography, my Art: the world seen by my lens. "
# Keywords/tags for you site.
keywords: "nizar souissi, nezar souissi, photography, nezar souissi photography, niz'art photography, niz'art, nizar, nezar, souissi, zanzoor, dubai, tunis, tunisia, munich, alps, photography, blog, photography-blog, photo-blog"
# Your copyright message.
copyright: "Copyright &copy; 2022 - Nizar Souissi."

language: "en-US"

## Site Configurations ##
# 1st heading of the site.
header: "Nizar's Photography"
# 2nd heading/sub heading of the website.
subheader: "Elastic Designs"
# A description/bio of the website.

# Facebook App ID
facebook_app_id: "702222463690498"

footer: 
  headline: "Photography is more than a hobby"
  text: "I am hobbyist photographer with love for open source software, passion for disruptive technologies (DLT, IoT, AI) and special care for sustainable development. I live between Tunisia, Germany, and Dubai. Photography is a fulfillment for me. I chase smiles, the most rewarding ones, those of camera-shy people when they discover how cute in reality they are. I shoot just for satisfaction, not professionally. If you like my work, get in touch ;-)"
  social_headline: "Follow me"

social:
  -
    label: "Twitter"
    url: "https://twitter.com/nezarsouissi"
    icon: "twitter"
  -
    label: "Facebook"
    url: "https://www.facebook.com/zphotons/"
    icon: "facebook"
  -
    label: "Instagram"
    url: "https://www.instagram.com/nezarsouissi/"
    icon: "instagram"
  -
    label: "Github"
    url: "https://github.com/nsoui"
    icon: "github"
  -
    label: "LinkedIn"
    url: "https://www.linkedin.com/in/nizarsouissi"
    icon: "linkedin"


contact:
  realEmail: "nizar@souissi.eu"
  headline: "Get in touch"
  buttonText: "Send"
  resetText: "Reset"
  name:
    text: "Name *"
    warning: "Please, enter your name"
  email:
    text: "Email *"
    warning: "Please, enter your email."
  message:
    text: "Message *"
    warning: "Please, enter your message"
  
# This is used as the link of the contact form. 
# Your Formspree.io link will look like this
# "https://formspree.io/f/{{ email }}"
email: "nizar@souissi.eu"

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
thumb_dir: "/gallery/thumbs"
small_pics_dir: "/gallery/small"
large_pics_dir: "/gallery/large"


## Make sure these values are also the same in the makefile
thumb_height: 250
thumb_quality: 75
small_width: 600
full_width: 1200
full_height: 900
    

# Any valid value of "background-position" CSS attribute.
image_position: "left center"

sass:
    sass_dir: _sass

## Jekyll Configuration ##
collections:
  authors:
    output: true

defaults:
  - scope:
    # Should be same as the `gallery_dir` key above.
      path: "gallery"
    values:
      image: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "_posts"
      type: "posts"
      output: true
      # permalink: /:collection/:name
      permalink: images/:title/
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


exclude:
  - vendor
  - Gemfile
  - OriginalPics


# Tags pages 
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
# 
