## Site Meta ##
# The title of the website.
title: Nizar's Photography
# The description of the website
tagline: My photography, my art
description: "My photography blog: the world through my lens."
# Keywords/tags for you site.
keywords: "nizar souissi, nezar souissi, photography, nezar souissi photography, niz'art photography, niz'art, nizar, nezar, souissi, zanzoor, dubai, tunis, tunisia, munich, alps, photography, blog, photography-blog, photo-blog"
# Your copyright message.
copyright: "Copyright &copy; 2022 - Nizar Souissi."
logo: /assets/images/logo.webp
language: "en-US"

url: "https://souissi.eu"

## Site Configurations ##
# 1st heading of the site.
header: "Nizar's Photography"

# Facebook App ID
facebook:
  app_id: "702222463690498"
  publisher: "https://www.facebook.com/zphotons"
  admins: "https://www.facebook.com/nizar.souissi/"

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
  facebook: 1234


footer: 
  headline: "Photography is more than a hobby"
  text: "I am hobbyist photographer with love for open source software, passion for disruptive technologies (DLT, IoT, AI) and special care for sustainable development. I live between Tunisia, Germany, and Dubai. Photography is a fulfillment for me. I chase smiles, the most rewarding ones, those of camera-shy people when they discover how cute in reality they are. I shoot just for satisfaction, not professionally. If you like my work, get in touch ;-)"
  social_headline: "Follow me"

social:
  name: Nizar Souissi
  links:
    - https://twitter.com/nezarsouissi
    - https://www.facebook.com/nizar.souissi
    - https://www.linkedin.com/in/nizarsouissi
    - https://github.com/nsoui
    - https://www.instagram.com/nezarsouissi/
  buttons:
    -
      label: "Twitter"
      url: "https://twitter.com/nezarsouissi"
      icon: "twitter"
    -
      label: "Facebook"
      url: "https://www.facebook.com/zphotons/"
      icon: "facebook"
    -
      label: "Instagram"
      url: "https://www.instagram.com/nezarsouissi/"
      icon: "instagram"
    -
      label: "Github"
      url: "https://github.com/nsoui"
      icon: "github"
    -
      label: "LinkedIn"
      url: "https://www.linkedin.com/in/nizarsouissi"
      icon: "linkedin"

contact:
  realEmail: "nizar@souissi.eu"
  headline: "Get in touch"
  formsphere:
    email: "nizar@souissi.eu"
  buttonText: "Send"
  resetText: "Reset"
  name:
    text: "Name *"
    warning: "Please, enter your name"
  email:
    text: "Email *"
    warning: "Please, enter your email."
  message:
    text: "Message *"
    warning: "Please, enter your message"
  
# This is used as the link of the contact form. 
# Your Formspree.io link will look like this
# "https://formspree.io/f/{{ email }}"


## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
thumb_dir: "/gallery/thumbs"
large_thumb_dir: "/gallery/lrgthumbs"
small_pics_dir: "/gallery/pics"
large_pics_dir: "/gallery/lrgpics"
static_images_folder: "/assets/images"


## Make sure these values are also the same in the makefile
thumb_height: 250
thumb_quality: 75
small_width: 600
full_width: 1200
full_height: 900
    

# Any valid value of "background-position" CSS attribute.
image_position: "left center"

sass:
    sass_dir: _sass
    style: compressed



exclude:
  - vendor
  - Gemfile
  - OriginalPics
  - firebase.json
  - .firebase
  - makefile
  - firebase-debug.log
  - README.md
  - LICENSE
  - _build
  - _site

# Tags pages 
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
# 

permalink: /posts/:title:output_ext

# plugins:
#   - jekyll-seo-tag
plugins:
  - jekyll-image-size